import * as Yup from 'yup'

export const PersonalInfoFieldConfigs = [
	{
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		placeholder: 'Enter your first name',
		label: 'First Name',
		required: true,
		validation: Yup.string().required('First Name is required'),
	},
	{
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		placeholder: 'Enter your last name',
		label: 'Last Name',
		required: true,
		validation: Yup.string().required('Last Name is required'),
	},
	{
		id: 'gender',
		name: 'gender',
		type: 'select',
		placeholder: 'Select your gender',
		label: 'Gender',
		required: true,
		options: [
			{ value: 'male', label: 'Male' },
			{ value: 'female', label: 'Female' },
		],
		validation: Yup.string().required('Gender is required'),
	},
	{
		id: 'dateOfBirth',
		name: 'dateOfBirth',
		type: 'date_picker',
		placeholder: 'Select your date of birth',
		label: 'Date of Birth',
		required: true,
		validation: Yup.date().required('Date of Birth is required'),
	},
	{
		id: 'phoneNumber',
		name: 'phoneNumber',
		type: 'text',
		placeholder: 'Enter your phone number',
		label: 'Phone Number',
		required: true,
		validation: Yup.string().required('Phone Number is required'),
	},
	{
		id: 'email',
		name: 'email',
		type: 'text',
		placeholder: 'Enter your email address',
		label: 'Email',
		required: true,
		validation: Yup.string()
			.email('Invalid email format')
			.required('Email is required'),
	},
]

export const ClinicalFindingsFieldConfigs = [
	{
		id: 'chiefComplaint',
		name: 'chiefComplaint',
		type: 'text_area',
		placeholder: 'Enter the chief complaint',
		label: 'Chief Complaint',
		required: true,
		validation: Yup.string().required('Chief Complaint is required'),
	},
	{
		id: 'historyOfPresentIllness',
		name: 'historyOfPresentIllness',
		type: 'text_area',
		placeholder: 'Enter the history of present illness',
		label: 'History of Present Illness',
		required: true,
		validation: Yup.string().required('History of Present Illness is required'),
	},
	{
		id: 'pastMedicalHistory',
		name: 'pastMedicalHistory',
		type: 'text_area',
		placeholder: 'Enter the past medical history',
		label: 'Past Medical History',
		required: false,
		validation: Yup.string(),
	},
	{
		id: 'physicalExam',
		name: 'physicalExam',
		type: 'text_area',
		placeholder: 'Enter the findings from the physical exam',
		label: 'Physical Exam',
		required: true,
		validation: Yup.string().required('Physical Exam is required'),
	},
	{
		id: 'diagnosis',
		name: 'diagnosis',
		type: 'text_area',
		placeholder: 'Enter the diagnosis',
		label: 'Diagnosis',
		required: true,
		validation: Yup.string().required('Diagnosis is required'),
	},
	{
		id: 'treatmentPlan',
		name: 'treatmentPlan',
		type: 'text_area',
		placeholder: 'Enter the treatment plan',
		label: 'Treatment Plan',
		required: true,
		validation: Yup.string().required('Treatment Plan is required'),
	},
]
