version: '3.8'

services:
  frontend:
    build: .
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sample.redwanjemal.dev`)"
      - 'traefik.http.routers.it-tools.entrypoints=https'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
networks:
  proxy:
    external: true
